config/routes.rb
Rails.application.routes.draw do
  resources :webhook_endpoints
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
end

app/models/webhook_endpoint.rb
class WebhookEndpoint < ApplicationRecord
    before_save :generate_secret, :generate_queue_name

    validates :api_url, :client_name, presence: true

    def generate_secret
        self.secret = SecureRandom.hex(16)
    end

    def generate_queue_name
        self.queue_name = client_name.parameterize.underscore + SecureRandom.hex(4)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        Publisher.publish("articles", @article.attributes.merge(event_type: 'created'))
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        Publisher.publish("articles", @article.attributes.merge(event_type: 'updated'))
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/concerns/sneakers_builder/sneakers_workers_builder.rb
module SneakersBuilder
  class SneakersWorkersBuilder
    class << self
      def call(klass_name, queue_name, queue_options, &message_handler)
        Object.const_set(klass_name.classify, Class.new do
         include SneakersBuilder::Workable

         define_work_method(
           queue_name: queue_name, queue_options: queue_options, &message_handler
         )
        end)
      end
    end
  end
end

app/controllers/concerns/sneakers_builder/workable.rb
module SneakersBuilder
    module Workable
      extend ActiveSupport::Concern
  
      included do
        include Sneakers::Worker
      end
  
      class_methods do
        def define_work_method(queue_name:, queue_options:)
          define_queue_options(queue_name, queue_options)
          define_method(:work) do |message|      
            yield(message) if block_given?
            ack!       
          end
        end
  
        private
  
        def define_queue_options(queue_name, queue_options)
          from_queue(
            queue_name, queue_options
          )
        end
      end
    end
  end

app/controllers/webhook_endpoints_controller.rb
class WebhookEndpointsController < ApplicationController
  include SneakersBuilder::SneakersWorkersBuilder 
  before_action :set_webhook_endpoint, only: %i[ show edit update destroy ]

  # GET /webhook_endpoints or /webhook_endpoints.json
  def index
    @webhook_endpoints = WebhookEndpoint.all
  end

  # GET /webhook_endpoints/1 or /webhook_endpoints/1.json
  def show
  end

  # GET /webhook_endpoints/new
  def new
    @webhook_endpoint = WebhookEndpoint.new
  end

  # GET /webhook_endpoints/1/edit
  def edit
  end

  # POST /webhook_endpoints or /webhook_endpoints.json
  def create
    @webhook_endpoint = WebhookEndpoint.new(webhook_endpoint_params)

    respond_to do |format|
      if @webhook_endpoint.save
        CreateQueue.add('articles', @webhook_endpoint.queue_name)
        
        queue_name = "#{@webhook_endpoint.queue_name}"
        klass_name = "#{@webhook_endpoint.queue_name}_worker"
        
        ## Temp: Issue creating workers for each queue dynamically

        # SneakersBuilder::SneakersWorkersBuilder.call(klass_name, queue_name) do |message|
        #   WebhookService.call(message)
        # end

        format.html { redirect_to webhook_endpoint_url(@webhook_endpoint), notice: "Webhook endpoint was successfully created." }
        format.json { render :show, status: :created, location: @webhook_endpoint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webhook_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhook_endpoints/1 or /webhook_endpoints/1.json
  def update
    respond_to do |format|
      if @webhook_endpoint.update(webhook_endpoint_params)
        format.html { redirect_to webhook_endpoint_url(@webhook_endpoint), notice: "Webhook endpoint was successfully updated." }
        format.json { render :show, status: :ok, location: @webhook_endpoint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webhook_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhook_endpoints/1 or /webhook_endpoints/1.json
  def destroy
    @webhook_endpoint.destroy

    respond_to do |format|
      format.html { redirect_to webhook_endpoints_url, notice: "Webhook endpoint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook_endpoint
      @webhook_endpoint = WebhookEndpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webhook_endpoint_params
      params.require(:webhook_endpoint).permit(:client_name, :api_url, :secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/webhook_endpoints_helper.rb
module WebhookEndpointsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebhookWithRabbitmq</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/webhook_endpoints/_form.html.erb
<%= form_with(model: webhook_endpoint) do |form| %>
  <% if webhook_endpoint.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(webhook_endpoint.errors.count, "error") %> prohibited this webhook_endpoint from being saved:</h2>

      <ul>
        <% webhook_endpoint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_name, style: "display: block" %>
    <%= form.text_field :client_name %>
  </div>

  <div>
    <%= form.label :api_url, style: "display: block" %>
    <%= form.text_field :api_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/webhook_endpoints/_webhook_endpoint.html.erb
<div id="<%= dom_id webhook_endpoint %>">
  <p>
    <strong>Client name:</strong>
    <%= webhook_endpoint.client_name %>
  </p>

  <p>
    <strong>Api url:</strong>
    <%= webhook_endpoint.api_url %>
  </p>

  <p>
    <strong>Secret:</strong>
    <%= webhook_endpoint.secret %>
  </p>

</div>

app/views/webhook_endpoints/edit.html.erb
<h1>Editing webhook endpoint</h1>

<%= render "form", webhook_endpoint: @webhook_endpoint %>

<br>

<div>
  <%= link_to "Show this webhook endpoint", @webhook_endpoint %> |
  <%= link_to "Back to webhook endpoints", webhook_endpoints_path %>
</div>

app/views/webhook_endpoints/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Webhook endpoints</h1>

<div id="webhook_endpoints">
  <% @webhook_endpoints.each do |webhook_endpoint| %>
    <%= render webhook_endpoint %>
    <p>
      <%= link_to "Show this webhook endpoint", webhook_endpoint %>
    </p>
  <% end %>
</div>

<%= link_to "New webhook endpoint", new_webhook_endpoint_path %>

app/views/webhook_endpoints/new.html.erb
<h1>New webhook endpoint</h1>

<%= render "form", webhook_endpoint: @webhook_endpoint %>

<br>

<div>
  <%= link_to "Back to webhook endpoints", webhook_endpoints_path %>
</div>

app/views/webhook_endpoints/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @webhook_endpoint %>

<div>
  <%= link_to "Edit this webhook endpoint", edit_webhook_endpoint_path(@webhook_endpoint) %> |
  <%= link_to "Back to webhook endpoints", webhook_endpoints_path %>
  <%= button_to "Destroy this webhook endpoint", @webhook_endpoint, method: :delete %>
</div>